---
contact_links:
  - name: Ask a question or get support (Forum)
    url: https://github.com/astronomer/airflow-dbcleanup-plugin/discussions/
    about: Ask a question or request support for using this package
